biotope/biotope-build

lib/hbs-parser.js
tasks/hb.js

renamed template variable to templateInfo

fixed an issue with debugging

---

README.md
config.js

Default values 100 on unix, 250 on windows.

added default values for polling intervall to reduce windows cpu usage

---

index.js
tasks/browserSupport.js
tasks/hb.js

adds a gulp task to create a browser matrix out of a json file

add browserSupport task

---

lib/hbs-helpers.js
lib/hbs-parser.js
lib/icon-parser.js
lib/json-parser.js
tasks/browserSupport.js
tasks/checkDependencies.js
tasks/clean.js
tasks/cleanCss.js
tasks/connect.js
tasks/copy.js
tasks/cssstats.js
tasks/eslint.js
tasks/favicons.js
tasks/handlebars.js
tasks/hb.js
tasks/htmlhint.js
tasks/iconfont.js
tasks/image.js
tasks/inject.js
tasks/jshint.js
tasks/json.js
tasks/modernizr.js
tasks/sass.js
tasks/uglify.js
tasks/useref.js
tasks/webpack.js

@alxbenz   I moved most requires into the functions. For me it starts much faster now and is about 10% faster in total (for build task).
I have found 2 issues that are not yet fixed in this branch and break the build process:
- no SVGs for iconfont 
- no browserSupport file
I try to fix those bugs tomorrow, either in this or the target branch. Or call me if you fix those issues in the meantime..

5.2.0 rc1 lazy

---

lib/hbs-helpers.js

Output name of missing partial in console.log

---

tasks/uglify.js

Need to call cb() when uglify is set to false in projectConfig.js

callback function added if uglify=false

---

tasks/useref.js

added bio helpers

---

tasks/iconfont.js

This fixes the error as it checks if file path exists

🐛 Iconfont folder is needed for build #79

---

tasks/iconfont.js

Reverts biotope/biotope-build#90

Revert "🐛 Iconfont folder is needed for build #79"

---

tasks/iconfont.js

Updated version. Forgot to filter for *errors*. Tested it in two projects and it seems to work now 👍 Sorry for the troubles ✌️

Fix iconfont error

---

package.json
pumps/uglify.js
tests/uglify.js
yarn.lock

Fix uglify for ES6

---

config.js

fix for iconfont

---

lib/env-helper.js
lib/hb2-helpers.js
webpack.config.js

add env var support

---

webpack.config.js

Fixes https://github.com/biotope/biotope-build/issues/129

add node_modules path to default include path in webpack config

---

CHANGELOG.md
config.js
lib/env-helper.js
package.json
tasks/hb2.js
yarn.lock

https://github.com/biotope/biotope-build/issues/131
https://github.com/biotope/biotope-build/issues/132

Env to hbs data

---

tasks/sass.js

cache sass compile streams to compile only changed files
#139

https://github.com/biotope/biotope-build/issues/139

---

index.js
tasks/sass.js

Refactored the whole sass task to only use one task for resources and components.
Fixes https://github.com/biotope/biotope-build/issues/145

Refactor sass

---

index.js
tasks/useref.js

Useref fix minify charset

---

tasks/iconfont.js

remove eot

---

config.js
package.json
tasks/connect.js

I've added the possibility to change the hostname of the connect server. That change make it easier to run biotope development with a docker backend.

make host configurable

---

tasks/iconfont.js
tasks/uglify.js

Adds error handling for promises, where they are used.

add catches for silent errors

---

index.js
tasks/copy.js

🐛 fix: copy _assets folder from src to dist

---

webpack.config.js

fix webpack config that it works for projects without bio-element

---

package-lock.json
package.json
webpack.config.js

feat: 🎸 add autoprefixer to webpack

---

config.js
tasks/sass.js

change request from the UI Team

feat: 🎸 exclude paths for sass task
